### ISSUE TITLE
PHP7 Exception

### ISSUE THREAD

**Issue by ghost** [OmarElGabry/miniPHP#12]
Uncaught TypeError: Argument 1 passed to Handler::render() must be an instance of Exception, instance of Error given

Didn't have time to track this issue on a general way but it's on line 78

**Comment by OmarElgabry** [comment]
This is because Backward incompatible changes in PHP 7. According to the [documentation](http://php.net/manual/en/migration70.incompatible.php), the exception handler should either receive an object of type `Throwable` instead of `Exception`(works for PHP 7 only), OR don't define type declaration at all(works for PHP 5 & 7). Another solution is to check if `$e` is instance of `Error` in `handleException` method, If so, then assign `$e` to `new ErrorException($e->getMessage(), ....)`.

This is because many fatal errors throws exceptions in PHP 7. Given that, all `exceptions` and `Error` class inherit from the `Throwable` interface. So, they share the same methods. This is [how errors operate in PHP 7](http://php.net/manual/en/language.errors.php7.php).

**Comment by ghost** [comment]
Thnx Omar, I knew that already but for some reason it doesn't fit, empty pages as result but I think I've missed a typo? Correct some of them and the error is gone.

**Comment by OmarElgabry** [comment]
It's fixed now. Thanks.
