### ISSUE TITLE
Class 'AuthComponent' not found

### ISSUE THREAD

**Issue by nakous** [OmarElGabry/miniPHP#23]
When i installed this Mvc in my local Xampp it work correctly ,but when i migrate project in my server it give me this issue :

Fatal error: Class 'AuthComponent' not found in /home/dfpdevshopify/public_html/app/core/Controller.php on line 119.

plz if you have any idea share it with me

**Comment by OmarElgabry** [comment]
You need to make sure these classes are already autoloaded by the composer. It seems that the only classes that aren't autoloaded are those in the `app/core/Components` folder.

Try to put slash `/` after `app/core/Components` in the `composer.json` file. Don't forget to re-run the `composer.json` file again on your production environment. Did it work?

**Comment by Damnmind** [comment]
Hey, i had same issue, moved my project to vps and cant start it up.

After adding slash after `app/core/Components `(and also change Components to components), i had some progress, login page appears.
Also i had mod_rewrite disabled, now its enabled.

After login attempt, error 500 appears.
Log file says:
```
13/06/2017 10:41:11 | /var/www/####/app/core/Controller.php | 229 | ErrorException
Class 'login' not found
*******************************************************************
```

My vps have 14.04 ubuntu, Apache/2.4.7 (Ubuntu), PHP 5.5.9.

I assume problem may be in apache/php configurations, but not sure, still trying to find out problem.

**Comment by OmarElgabry** [comment]
You probably get this problem when the `Login `model [gets loaded in the Controller](https://github.com/OmarElGabry/miniPHP/blob/master/app/core/Controller.php#L236). Since the model name starts with upper case (It's `Login `not `login`), the method converts the first letters to upper case. Although this might not be a problem in some situations; you can load the model just fine using lower case (`login `instead of `Login`).

**Comment by Damnmind** [comment]
I was using version from release one, not the actual git, i copied model load function you posted above to my project and all works, thank you!
